name: Build Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_in_container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag os-testing:$(date +%s)
  build_executables:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14.0'
    - run: |
        cd os-testing-app
        env GOOS=linux GOARCH=amd64 go build -o packages/linux-os-testing main.go
        env GOOS=windows GOARCH=amd64 go build -o packages/windows-os-testing main.go
        echo "Executable Files" >> README.md
        ls packages
    - uses: actions/upload-artifact@v2
      with:
        name: os-testing-packages
        path: ${{ github.workspace }}/os-testing-app/packages/*
        if-no-files-found: error
