name: Build and Test Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag os-testing:$(date +%s)
    - name: Run the Docker image
      run: docker run --rm os-testing:$(date +%s)
